services:
  keycloak:
    environment:
      KEYCLOAK_ENABLE_HTTPS: "true"
      KEYCLOAK_HTTPS_USE_PEM: "true"
      KEYCLOAK_HTTPS_CERTIFICATE_FILE: /opt/bitnami/keycloak/certs/tls.crt
      KEYCLOAK_HTTPS_CERTIFICATE_KEY_FILE: /opt/bitnami/keycloak/certs/tls.key
      KEYCLOAK_EXTRA_ARGS: "--import-realm"
    volumes:
      - ./helm/api-platform/keycloak/certs/tls.crt:/opt/bitnami/keycloak/certs/tls.crt:ro
      - ./helm/api-platform/keycloak/certs/tls.pem:/opt/bitnami/keycloak/certs/tls.key:ro
      - ./helm/api-platform/keycloak/config:/opt/bitnami/keycloak/data/import
